
{% set name = "piano_fingering" %}
{% set version = "1.0.0" %}

package:
  name: piano_fingering
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/piano_fingering/piano_fingering-{{ version }}.tar.gz
  sha256: 737011b979f62742109842c654734167051ea402a545de542e03e915b577070f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
test:
  imports:
    - piano_fingering
  commands:
    - pip check
  requires:
    - pip
about:
  home: https://github.com/Kanma/piano_fingering
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  description: |
    A Python library to automatically determine the fingering of a serie of notes.
    The algorithm is adapted from the corresponding one from 
    https://github.com/blakewest/performer, by Blake West.

  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://github.com/Kanma/piano_fingering
  dev_url: https://github.com/Kanma/piano_fingering

extra:
  recipe-maintainers:
    - betofraus
